INSERT INTO ccas
	VALUES
		(1, 'Japanese Appreciation Club', 'Arts and Cultural', 'JAC Description', 'JAC Schedule', 'JAC Venue', 'JAC Contact', 1, '2018-01-06 00:00:00', null, null, null, null, b'0'),
        (2, 'NTU Sports Club', 'Special Interest', 'SC Nutrition', 'SC Schedule', 'SC Venue', 'SC Contact', 1, '2018-01-06 00:00:00', null, null, null, null, b'0');

INSERT INTO events
	VALUES
		(1, 1, 'JAC New Year Party', 'Celebration', 'To welcome the new academic year, we’ll be hosting a party! There’ll be delicious Japanese food from Miz restaurant, fun games and prizes to be won! We hope to see you there!', 'https://images.pexels.com/photos/1268558/pexels-photo-1268558.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260', '2019-01-11 00:00:00', '2019-01-11 00:00:00', 'Spottiswoode condominum 48', null, 'JAC Contact', 'JAC Website', null, null, null, null, null, null, b'0'),
        (2, 2, 'Surf N Sweat', 'Sports', 'Surf N Sweat is Singapore''s largest annual beach sporting event, proudly organised by Nanyang Technological University Sports Club. We''ll be making waves at Palawan Beach, Sentosa, so prepare yourself for a day of adrenaline pumping and exhilarating activities happening on both sand and sea!', 'http://surfnsweat.ntusportsclub.sg/images/img_8895-crop-u2764.jpg?crc=4203607046', '2019-02-17 00:00:00', '2019-02-17 00:00:00', 'Palawan Beach, Sentosa', null, 'SC Contact', 'SC Website', null, null, null, null, null, null, b'0'),
        (3, 2, 'Bike Rally', 'Sports', 'Bike Rally is a nationwide, non-competitive cycling event organised by Nanyang Technological University (NTU) Sports Club. It aims to connect both amateur and professional cyclists through their shared love for cycling.', 'http://bikerally.ntusportsclub.sg/images/regpic.jpg', null, null, 'TBC', null, 'SC Contact', 'SC Website', null, null, null, null, null, null, b'0');